import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Nextjs Sok",
    template: "%s | happy coding",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <div className=" bg-slate-400 text-rose-500 text-2xl text-center">
          header
        </div> */}
        {children}
        {/* <div className=" bg-slate-400 text-rose-500 text-2xl text-center">
          footer
        </div> */}
      </body>
    </html>
  );
}
